"""creata operation

Revision ID: fe929b193378
Revises: e426193921df
Create Date: 2023-12-30 21:34:37.933803

"""
from typing import Sequence, Union

# import sqlalchemy as sa
# from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe929b193378"
down_revision: Union[str, None] = "e426193921df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
